"""Parse the pinned Qdrant repository and GitHub export into stable document units."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

from common import (WORK, admit_read, atomic_write_bytes, registry, sha_bytes, sha_file,
                    sha_json, write_json)

TEXT_EXTENSIONS = {".md", ".mdx", ".rst", ".adoc", ".txt"}
SOURCE_EXTENSIONS = {".rs", ".py", ".js", ".ts", ".go", ".proto", ".toml", ".yaml", ".yml"}
BOT_BOILERPLATE = (
    re.compile(r"(?is)<!--.*?-->"),
    re.compile(r"(?im)^\s*(?:please fill|checklist|generated by|this is an automated).*$"),
)
SECRET_PATTERNS = (
    ("private_key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----.*?-----END [A-Z ]*PRIVATE KEY-----", re.S)),
    ("github_token", re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})\b")),
    ("aws_key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("bearer", re.compile(r"(?i)\bBearer\s+[A-Za-z0-9._~+/=-]{16,}")),
    ("assigned_secret", re.compile(r"(?i)\b(password|passwd|secret|api[_-]?key|token)\s*[:=]\s*['\"]?[^\s'\"]{8,}")),
)


def normalize_space(text):
    return re.sub(r"\s+", " ", str(text)).strip()


def redact(text):
    out = str(text or "")
    counts = Counter()
    for name, rx in SECRET_PATTERNS:
        out, n = rx.subn(f"<REDACTED_{name.upper()}>", out)
        counts[name] += n
    return out, dict(counts)


def clean_body(text, is_bot=False):
    text, redactions = redact(text)
    if is_bot:
        for rx in BOT_BOILERPLATE:
            text = rx.sub("", text)
    # Collapse quote-only history but retain explanatory prose and fenced logs/stack traces.
    lines, quoted = [], 0
    for line in text.splitlines():
        if line.lstrip().startswith(">"):
            quoted += 1
            continue
        lines.append(line.rstrip())
    return "\n".join(lines).strip(), redactions, quoted


def stable_id(kind, source_id, part=0):
    return f"{kind}:{source_id}" + (f":{part}" if part else "")


def _chunks(text, limit=384, overlap=48):
    """Section-aware whitespace-token chunks; code fences remain beside surrounding prose."""
    text = str(text).strip()
    if not text:
        return []
    sections, heading, buf = [], "", []
    for line in text.splitlines():
        if re.match(r"^#{1,6}\s+\S", line) and buf:
            sections.append((heading, "\n".join(buf)))
            heading, buf = line.lstrip("# ").strip(), [line]
        else:
            if not buf and re.match(r"^#{1,6}\s+\S", line):
                heading = line.lstrip("# ").strip()
            buf.append(line)
    if buf:
        sections.append((heading, "\n".join(buf)))
    out = []
    for heading, section in sections:
        words = section.split()
        if len(words) <= limit:
            out.append((heading, section.strip()))
            continue
        step = max(1, limit - overlap)
        for lo in range(0, len(words), step):
            part = " ".join(words[lo:lo + limit])
            if part:
                out.append((heading, part))
            if lo + limit >= len(words):
                break
    return out


def _source_comments(text, suffix):
    """Contiguous explanatory comment blocks, never isolated source lines."""
    prefixes = ("///", "//!", "//") if suffix in {".rs", ".js", ".ts", ".go", ".proto"} else ("#",)
    blocks, current = [], []
    for line in text.splitlines():
        stripped = line.strip()
        hit = next((p for p in prefixes if stripped.startswith(p)), None)
        if hit:
            body = stripped[len(hit):].strip()
            current.append(body)
        else:
            if len(current) >= 2 and len(" ".join(current)) >= 80:
                blocks.append("\n".join(current))
            current = []
    if len(current) >= 2 and len(" ".join(current)) >= 80:
        blocks.append("\n".join(current))
    return blocks


def parse_repository(checkout, commit, chunk_tokens=384, overlap=48):
    checkout = Path(checkout)
    got = subprocess.run(["git", "rev-parse", "HEAD"], cwd=checkout, text=True,
                         capture_output=True, check=True).stdout.strip()
    if got != commit:
        raise SystemExit(f"M18 CORPUS REFUSED: checkout is {got}, registry pins {commit}")
    dirty = subprocess.run(["git", "status", "--porcelain", "--untracked-files=no"], cwd=checkout,
                           text=True, capture_output=True, check=True).stdout.strip()
    if dirty:
        raise SystemExit("M18 CORPUS REFUSED: pinned checkout has modified tracked files")
    names = subprocess.run(["git", "ls-tree", "-r", "--name-only", commit], cwd=checkout,
                           text=True, capture_output=True, check=True).stdout.splitlines()
    redactions = Counter()
    for rel in sorted(names):
        path = Path(rel)
        suffix = path.suffix.lower()
        if suffix not in TEXT_EXTENSIONS | SOURCE_EXTENSIONS:
            continue
        try:
            # Read the registered Git object, not mutable worktree bytes.
            blob = subprocess.run(["git", "show", f"{commit}:{rel}"], cwd=checkout,
                                  capture_output=True, check=True).stdout
            text = blob.decode("utf-8", errors="replace")
        except (OSError, UnicodeError, subprocess.CalledProcessError):
            continue
        text, reds = redact(text); redactions.update(reds)
        if suffix in TEXT_EXTENSIONS:
            for i, (heading, body) in enumerate(_chunks(text, chunk_tokens, overlap), 1):
                if len(normalize_space(body)) < 40:
                    continue
                yield {"doc_id": stable_id("repo", rel, i), "kind": "repository_text",
                       "artifact_id": f"repo:{rel}", "path": rel, "symbol": heading,
                       "text": body, "title": heading or Path(rel).name,
                       "source_url": f"https://github.com/qdrant/qdrant/blob/{commit}/{rel}",
                       "timestamp": None, "author_association": None, "outbound_links": []}
        elif suffix in SOURCE_EXTENSIONS:
            for i, body in enumerate(_source_comments(text, suffix), 1):
                yield {"doc_id": stable_id("code_comment", rel, i), "kind": "code_comment",
                       "artifact_id": f"repo:{rel}", "path": rel, "symbol": "",
                       "text": body, "title": f"Comments in {rel}",
                       "source_url": f"https://github.com/qdrant/qdrant/blob/{commit}/{rel}",
                       "timestamp": None, "author_association": None, "outbound_links": []}
    parse_repository.stats = {"redactions": dict(redactions), "tracked_files_considered": len(names)}


def iter_api_objects(raw_root, endpoint):
    base = Path(raw_root) / "github" / endpoint / "pages"
    pages = sorted(base.glob("*.json"))
    if not pages:  # accept fixture/simple historical layouts
        pages = sorted((Path(raw_root) / "api" / endpoint).glob("**/page-*.json"))
    for page in pages:
        payload = json.loads(admit_read(page).read_text())
        if not isinstance(payload, list):
            raise SystemExit(f"M18 CORPUS REFUSED: {page} is not a JSON list")
        yield from payload


def _links(text):
    return sorted(set(re.findall(r"https?://[^\s)>\]]+", text or "")))


def _discussion_units(base, body, chunk_tokens, overlap):
    chunks = _chunks(body, chunk_tokens, overlap)
    for i, (_, part) in enumerate(chunks, 1):
        row = dict(base)
        row["doc_id"] = stable_id(base["doc_id"], "chunk", i) if len(chunks) > 1 else base["doc_id"]
        row["text"] = part
        row["chunk_index"] = i
        row["chunk_count"] = len(chunks)
        yield row


def parse_github(raw_root, cutoff, chunk_tokens=384, overlap=48):
    issues = {}
    redactions = Counter()
    quoted = 0
    for row in iter_api_objects(raw_root, "issues"):
        if str(row.get("created_at") or "") > cutoff:
            continue
        key = row.get("node_id") or f"issue:{row.get('id')}"
        if key in issues:
            continue
        issues[key] = row
        number = int(row["number"])
        title, title_reds = redact(row.get("title") or "")
        body, reds, q = clean_body(row.get("body") or "", str(row.get("user", {}).get("type")) == "Bot")
        redactions.update(title_reds)
        redactions.update(reds); quoted += q
        text = (title.strip() + "\n\n" + body).strip()
        if text:
            base = {"doc_id": stable_id("gh_opening", number),
                   "kind": "pull_request_opening" if row.get("pull_request") else "issue_opening",
                   "artifact_id": f"gh:thread:{number}", "github_node_id": row.get("node_id"),
                   "github_id": row.get("id"), "github_number": number,
                   "title": title, "text": text, "path": None, "symbol": None,
                   "source_url": row.get("html_url"), "timestamp": row.get("created_at"),
                   "updated_at": row.get("updated_at"),
                   "author": (row.get("user") or {}).get("login"),
                   "author_association": row.get("author_association"),
                   "state": row.get("state"), "closed_at": row.get("closed_at"),
                   "outbound_links": _links(text), "labels": [x.get("name") for x in row.get("labels", [])]}
            yield from _discussion_units(base, text, chunk_tokens, overlap)
    for endpoint, prefix, kind, thread_field in (
        ("issue_comments", "gh_issue_comment", "issue_comment", "issue_url"),
        ("review_comments", "gh_review_comment", "review_comment", "pull_request_url")):
        seen = set()
        for row in iter_api_objects(raw_root, endpoint):
            if str(row.get("created_at") or "") > cutoff:
                continue
            key = row.get("node_id") or f"{endpoint}:{row.get('id')}"
            if key in seen:
                continue
            seen.add(key)
            url = row.get(thread_field) or ""
            m = re.search(r"/(?:issues|pulls)/(\d+)$", url)
            if not m:
                continue
            number = int(m.group(1))
            is_bot = str((row.get("user") or {}).get("type")) == "Bot" or str(
                (row.get("user") or {}).get("login", "")).endswith("[bot]")
            body, reds, q = clean_body(row.get("body") or "", is_bot)
            redactions.update(reds); quoted += q
            if len(normalize_space(body)) < 20:
                continue
            base = {"doc_id": stable_id(prefix, row.get("id")), "kind": kind,
                   "artifact_id": f"gh:thread:{number}", "github_node_id": row.get("node_id"),
                   "github_id": row.get("id"), "github_number": number,
                   "title": "", "text": body, "path": row.get("path"), "symbol": None,
                   "source_url": row.get("html_url"), "timestamp": row.get("created_at"),
                   "updated_at": row.get("updated_at"),
                   "author": (row.get("user") or {}).get("login"),
                   "author_association": row.get("author_association"),
                   "in_reply_to_id": row.get("in_reply_to_id"), "outbound_links": _links(body)}
            yield from _discussion_units(base, body, chunk_tokens, overlap)
    for row in iter_api_objects(raw_root, "issue_events"):
        if str(row.get("created_at") or "") > cutoff:
            continue
        issue = row.get("issue") or {}
        number = issue.get("number")
        if number is None:
            for value in (row.get("issue_url"), issue.get("url"), issue.get("html_url")):
                m = re.search(r"/(?:issues|pulls?)/(\d+)(?:$|[?#])", str(value or ""))
                if m:
                    number = int(m.group(1)); break
        if number is None:
            continue
        event = str(row.get("event") or "event")
        details = [event]
        if row.get("label", {}).get("name"):
            details.append("label " + str(row["label"]["name"]))
        if row.get("rename"):
            details.append("renamed " + str(row["rename"].get("from", "")) + " to "
                           + str(row["rename"].get("to", "")))
        if row.get("commit_id"):
            details.append("commit " + str(row["commit_id"]))
        text, reds = redact("; ".join(details)); redactions.update(reds)
        links = []
        for value in (row.get("commit_url"), issue.get("html_url"), row.get("url")):
            if value:
                links.append(str(value))
        yield {"doc_id": stable_id("gh_event", row.get("id")), "kind": "issue_event",
               "artifact_id": f"gh:thread:{int(number)}", "github_node_id": row.get("node_id"),
               "github_id": row.get("id"), "github_number": int(number), "title": event,
               "text": text, "path": None, "symbol": None, "source_url": row.get("url"),
               "timestamp": row.get("created_at"), "updated_at": None,
               "author": (row.get("actor") or {}).get("login"), "author_association": None,
               "outbound_links": sorted(set(links))}
    parse_github.stats = {"redactions": dict(redactions), "quoted_lines_removed": quoted,
                          "unique_issue_objects": len(issues)}


def _deduplicate(records):
    seen_ids, canonical = set(), {}
    kept, dup = [], []
    for row in records:
        if row["doc_id"] in seen_ids:
            raise SystemExit(f"M18 CORPUS REFUSED: duplicate stable id {row['doc_id']}")
        seen_ids.add(row["doc_id"])
        norm = normalize_space(row["text"]).lower()
        digest = hashlib.sha256(norm.encode()).hexdigest()
        row["normalized_text_sha256"] = digest
        # Preserve artifact-level coverage. Identical boilerplate in two distinct threads is a
        # split-family signal, not permission to erase one thread's answer document.
        key = (row["artifact_id"], digest)
        if key in canonical:
            dup.append({"doc_id": row["doc_id"], "canonical_doc_id": canonical[key],
                        "artifact_id": row["artifact_id"]})
            continue
        canonical[key] = row["doc_id"]
        kept.append(row)
    return kept, dup


def _verify_source(raw, reg):
    try:
        from source import _existing_pages
    except ImportError:  # pragma: no cover
        from m18src.source import _existing_pages
    combined_path = raw / "source-manifest.json"
    if not combined_path.exists():
        raise SystemExit("M18 CORPUS REFUSED: completed combined source manifest is absent")
    combined = json.loads(admit_read(combined_path).read_text())
    if combined.get("complete") is not True or combined.get("git", {}).get("head") != reg["source"]["commit"]:
        raise SystemExit("M18 CORPUS REFUSED: combined source manifest is incomplete or mismatched")
    github = combined.get("github", {})
    if github.get("complete") is not True or github.get("commit") != reg["source"]["commit"]:
        raise SystemExit("M18 CORPUS REFUSED: GitHub source manifest is incomplete or mismatched")
    for endpoint in reg["source"]["endpoints"]:
        name = endpoint["name"]
        pages = _existing_pages(raw, endpoint, int(reg["source"]["per_page"]),
                                str(reg["source"]["api_version"]))
        expected = github.get("endpoints", {}).get(name, {}).get("pages")
        if expected != len(pages):
            raise SystemExit(f"M18 CORPUS REFUSED: endpoint {name} receipt count mismatch")
    return combined


def build(raw_root=None, out_root=None, registry_data=None, fixture=False):
    reg = registry_data or registry()
    raw = Path(raw_root or WORK / "source")
    out = Path(out_root or WORK / "derived")
    out.mkdir(parents=True, exist_ok=True)
    c = reg["corpus"]
    source_manifest = None if fixture else _verify_source(raw, reg)
    rows = list(parse_repository(raw / "repository", reg["source"]["commit"],
                                 c["chunk_tokens"], c["chunk_overlap_tokens"]))
    rows.extend(parse_github(raw, reg["source"]["github_cutoff_utc"],
                             c["chunk_tokens"], c["chunk_overlap_tokens"]))
    rows, duplicates = _deduplicate(rows)
    if len(rows) > int(c["document_units_max"]):
        raise SystemExit(f"M18 CORPUS REFUSED: {len(rows)} units exceed cap; registered adjacent "
                         "low-information merge must be implemented before dropping artifacts")
    rows.sort(key=lambda x: x["doc_id"])
    payload = b"".join((json.dumps(r, sort_keys=True, ensure_ascii=False) + "\n").encode()
                       for r in rows)
    corpus_path = atomic_write_bytes(out / "corpus.jsonl", payload)
    dup_payload = b"".join((json.dumps(r, sort_keys=True) + "\n").encode() for r in duplicates)
    duplicate_path = atomic_write_bytes(out / "duplicates.jsonl", dup_payload)
    by_kind = Counter(r["kind"] for r in rows)
    artifacts = Counter(r["artifact_id"] for r in rows)
    manifest = {"_schema": "m18-corpus-manifest-v1", "commit": reg["source"]["commit"],
                "cutoff_utc": reg["source"]["github_cutoff_utc"], "documents": len(rows),
                "artifacts": len(artifacts), "by_kind": dict(sorted(by_kind.items())),
                "exact_duplicates_removed": len(duplicates),
                "redaction": {"github": getattr(parse_github, "stats", {}),
                              "repository": getattr(parse_repository, "stats", {})},
                "corpus_sha256": sha_file(corpus_path),
                "duplicates_sha256": sha_file(duplicate_path),
                "source_manifest_sha256": (source_manifest or {}).get("sha256", "fixture"),
                "versions": {k: reg["versions"][k] for k in (
                    "parser", "redaction", "deduplication", "chunking")}}
    manifest["sha256"] = sha_json(manifest)
    write_json(out / "corpus_manifest.json", manifest)
    if out_root is None:
        write_json(Path(__file__).resolve().parents[1] / "results/m18_corpus_manifest.json", manifest)
    return manifest


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--raw-root", default=None)
    ap.add_argument("--out-root", default=None)
    args = ap.parse_args(argv)
    print(json.dumps(build(args.raw_root, args.out_root), indent=1, sort_keys=True))


if __name__ == "__main__":
    main()
